---
abstract: 'Perl DNS mail exchange & email format validation module'
author:
  - 'The McGrail Foundation & Kevin A. McGrail <kevin.mcgrail-netvalidmx@mcgrail.com>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.64, CPAN::Meta::Converter version 2.150010'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Net-validMX
no_index:
  directory:
    - t
    - inc
requires:
  Net::DNS: '0.53'
  Test::More: '0'
version: v2.5.0
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
license: artistic
abstract: Perl DNS mail exchange & email format validation module
author: The McGrail Foundation & Kevin A. McGrail <kevin.mcgrail-netvalidmx@mcgrail.com>
